[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.22"
optimizer = true
optimizer_runs = 200
evmVersion = "shanghai"

fs_permissions = [
    { access = "read", path = "./script/input/"},
    { access = "read", path = "./out/"},
    { access = "read-write", path = "./script/output/"}
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
